// registre-se no rapidapi, assine o exercício db api e use sua chave de API aqui
// https://rapidapi.com/justin-WFnsXH_t6/api/exercisedb

export const rapidApiKey = "chave api rápida aqui";

export const sliderImages = [
    require("../assets/images/slide1.png"),
    require("../assets/images/slide3.png"),
    require("../assets/images/slide2.png"),
    require("../assets/images/slide4.png"),
    require("../assets/images/slide5.png"),
];

export const bodyParts = [
    {
        name: "back",
        image: require("../assets/images/back.png"),
    },
    {
        name: "cardio",
        image: require("../assets/images/cardio.png"),
    },

    {
        name: "lower arms",
        image: require("../assets/images/lowerArms.png"),
    },
    {
        name: "lower legs",
        image: require("../assets/images/lowerLegs.png"),
    },
    {
        name: "chest",
        image: require("../assets/images/chest.png"),
    },
    {
        name: "neck",
        image: require("../assets/images/neck.png"),
    },
    {
        name: "shoulders",
        image: require("../assets/images/shoulders.png"),
    },
    {
        name: "upper arms",
        image: require("../assets/images/upperArms.png"),
    },
    {
        name: "upper legs",
        image: require("../assets/images/upperLegs.png"),
    },
    {
        name: "waist",
        image: require("../assets/images/waist.png"),
    },
];

export const demoExercises = [
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/ZBdUybBsOJZxqq",
        id: "3220",
        instructions: [
            "Fique em pé com os pés afastados na largura dos ombros.",
            "Dobre os joelhos e abaixe o corpo até a posição de agachamento.",
            "Salte explosivamente para cima, estendendo as pernas e os braços.",
            "Enquanto estiver no ar, abra as pernas e leve os braços para os lados.",
            "Aterre suavemente com os pés afastados na largura dos ombros, dobrando os joelhos para absorver o impacto.",
            "Repita pelo número desejado de repetições.",
        ],
        name: "montado em saltos (masculino)",
        secondaryMuscles: ["quadríceps", "isquiotibiais", "panturrilhas"],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/cvknkoB1wdv77s",
        id: "3672",
        instructions: [
            "Fique em pé com os pés afastados na largura dos ombros.",
            "Dê um passo à frente com o pé direito, dobrando o joelho e abaixando o corpo em uma posição de estocada.",
            "Empurre com o pé direito e volte à posição inicial.",
            "Repita o movimento com o pé esquerdo, alternando as pernas a cada passo.",
            "Continue andando para frente e para trás, mantendo um ritmo constante.",
            "Repita pela duração ou número de repetições desejado.",
        ],
        name: "passo para frente e para trás",
        secondaryMuscles: [
            "quadríceps",
            "isquiotibiais",
            "glúteos",
            "panturrilhas",
        ],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/Yzjs053WanECXK",
        id: "3360",
        instructions: [
            "Comece de quatro, com as mãos diretamente sob os ombros e os joelhos diretamente sob os quadris.",
            "Levante ligeiramente os joelhos do chão, mantendo as costas retas e o núcleo engajado.",
            "Mova a mão direita e o pé esquerdo para frente simultaneamente, seguidos pela mão esquerda e pelo pé direito.",
            "Continue engatinhando para frente, alternando os movimentos das mãos e dos pés.",
            "Mantenha um ritmo constante e mantenha o núcleo tenso durante todo o exercício.",
            "Continue pela distância ou tempo desejado.",
        ],
        name: "urso rastejando",
        secondaryMuscles: ["núcleo", "ombros", "tríceps"],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/VhYJMVKNSofs9D",
        id: "1160",
        instructions: [
            "Comece em pé com os pés afastados na largura dos ombros.",
            "Abaixe o corpo até a posição de agachamento, dobrando os joelhos e colocando as mãos no chão à sua frente.",
            "Coloque os pés de volta na posição de flexão.",
            "Faça uma flexão, mantendo o corpo em linha reta.",
            "Salte os pés de volta para a posição de agachamento.",
            "Salte explosivamente, alcançando os braços acima da cabeça.",
            "Aterrisse suavemente e imediatamente abaixe as costas em uma posição de agachamento para iniciar a próxima repetição.",
        ],
        name: "agachamento",
        secondaryMuscles: [
            "quadríceps",
            "isquiotibiais",
            "bezerros",
            "ombros",
            "peito",
        ],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Máquina de Alavancagem",
        gifUrl: "https://v2.exercisedb.io/image/pNgtBASgUkfB3b",
        id: "2331",
        instructions: [
            "Ajuste a altura do assento e posicione-se no bicicleta cross trainer.",
             "Coloque os pés nos pedais e segure o guidão.",
             "Comece a pedalar com um movimento suave e controlado.",
             "Mantenha um ritmo constante e aumente a resistência se desejar.",
             "Continue pedalando durante a duração desejada do seu treino cardiovascular.",
        ],
        name: "treinador de ciclismo",
        secondaryMuscles: ["quadríceps", "isquiotibiais", "glúteos"],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "",
        equipment: "haltere",
        gifUrl: "https://v2.exercisedb.io/image/NvEGPiHWN-0dBO",
        id: "1201",
        instructions: [
            "Comece em pé, com os pés afastados na largura dos ombros e um haltere em cada mão.",
             "Abaixe o corpo até a posição de agachamento, colocando os halteres no chão à sua frente.",
             "Coloque os pés para trás em uma posição de flexão, mantendo o corpo em linha reta.",
             "Faça uma flexão, dobrando os cotovelos e abaixando o peito em direção ao chão.",
             "Salte com os pés em direção às mãos, aterrissando em uma posição agachada.",
             "Levante-se de forma explosiva, levantando os halteres do chão e trazendo-os até os ombros.",
             "Pressione os halteres acima da cabeça, estendendo totalmente os braços.",
             "Abaixe os halteres de volta aos ombros e repita toda a sequência pelo número desejado de repetições.",
        ],
        name: "burpee com halteres",
        secondaryMuscles: [
            "quadríceps",
             "isquiotibiais",
             "bezerros",
             "ombros",
             "tríceps",
             "essencial",
        ],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/m-cBLDwdpfL1LN",
        id: "3221",
        instructions: [
            "Fique em pé com os pés afastados na largura dos ombros.",
             "Dobre os joelhos e abaixe o corpo como se estivesse sentado em uma cadeira.",
             "Mantenha o peito erguido e o peso nos calcanhares.",
             "Pare por um momento na parte inferior e, em seguida, empurre os calcanhares para retornar à posição inicial.",
             "Repita pelo número desejado de repetições.",
        ],
        name: "flexões de meio joelho (masculino)",
        secondaryMuscles: ["quadríceps", "isquiotibiais", "glúteos"],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/dXJUgwQDbb4DWp",
        id: "3636",
        instructions: [
            "Fique de frente para uma parede com os pés afastados na largura do quadril.",
             "Coloque as mãos na parede para se apoiar.",
             "Envolva seu núcleo e levante o joelho direito em direção ao peito, enquanto mantém o pé esquerdo no chão.",
             "Troque rapidamente as pernas, trazendo o joelho esquerdo em direção ao peito e abaixando o pé direito.",
             "Continue alternando as pernas em um movimento de corrida, levantando os joelhos o mais alto possível.",
             "Mantenha um ritmo rápido e mantenha a parte superior do corpo estável durante todo o exercício.",
             "Repita pela duração ou número de repetições desejado.",
        ],
        name: "joelho alto contra a parede",
        secondaryMuscles: ["quadríceps", "isquiotibiais", "glúteos", "panturrilhas"],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/94ePXp-xmeMB-J",
        id: "0501",
        instructions: [
            "Comece em pé com os pés afastados na largura dos ombros.",
             "Abaixe o corpo até a posição de agachamento, colocando as mãos no chão à sua frente.",
             "Jogue os pés para trás, pousando em uma posição de flexão.",
             "Faça uma flexão, abaixando o peito até o chão e depois empurrando de volta para cima.",
             "Salte com os pés para frente, aterrissando em uma posição agachada.",
             "Salte explosivamente, alcançando os braços acima da cabeça.",
             "Aterre suavemente e imediatamente abaixe as costas para a posição de agachamento para iniciar a próxima repetição.",
        ],
        name: "jack burpee",
        secondaryMuscles: [
            "quadríceps",
            "isquiotibiais",
            "bezerros",
            "ombros",
            "tríceps",
            "essencial",
        ],
        target: "sistema cardiovascular",
    },
    {
        bodyPart: "cardio",
        equipment: "Peso Corporal",
        gifUrl: "https://v2.exercisedb.io/image/tqoEMpfmp0WWvi",
        id: "3224",
        instructions: [
            "Fique em pé com os pés juntos e os braços ao lado do corpo.",
             "Salte, afastando os pés e levantando os braços acima da cabeça.",
             "Ao pousar, volte rapidamente para a posição inicial.",
             "Repita pelo número desejado de repetições.",
        ],
        name: "jack jump (masculino)",
        secondaryMuscles: ["quadríceps", "panturrilhas"],
        target: "sistema cardiovascular",
    },
];
